In [1]:
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('dark_background')

# Question 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [2]:
q1=np.arange(2,51,3)
q1

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

# Question 2:
Accept two lists of 5 elements each from the user.
<br>Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [3]:
def add_2_list(lst):
    print('Enter numbers')
    for i in range(5):
        temp=int(input())
        lst.append(temp)

lst1=[]
lst2=[]
add_2_list(lst1)
print()
add_2_list(lst2)

lst1=np.array(lst1)
lst2=np.array(lst2)

print('\n',lst1+lst2)

print('\nSorted Arrays\n',np.sort(lst1),'\n',np.sort(lst2))

Enter numbers
3
8
5
7
6

Enter numbers
9
12
18
15
13

 [12 20 23 22 19]

Sorted Arrays
 [3 5 6 7 8] 
 [ 9 12 13 15 18]


# Question 3:
Write a code snippet to find the dimensions of a ndarray and its size.

In [4]:
lst3=np.arange(24).reshape(3,4,2)
print('type: ',type(lst3),'shape: ',lst3.shape,'\n')


print('Dimension of ndarray: ',np.ndim(lst3),'\n')

print('Size of ndarray: ',np.size(lst3))

type:  <class 'numpy.ndarray'> shape:  (3, 4, 2) 

Dimension of ndarray:  3 

Size of ndarray:  24


# Question 4:
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [5]:
# Creating a 1D array
lst5 = np.arange(10)
print(lst5.shape)

# Converting the 1D array to 2D array by inserting an axis at position 1
lst6 = np.expand_dims(lst5, axis=1)
print(lst6.shape)


# Converting the 1D array to 2D array by inserting an axis at position 0
lst6 = np.expand_dims(lst5, axis=0)
print(lst6.shape)

# Converting the 1D array to 3D array by inserting an axis at position 1,2
lst7=np.expand_dims(lst5,axis=(1,2))
print(lst7.shape)

# creating a 2D array
lst8= np.arange(25).reshape(5,5)
print(lst8.shape)

# Converting above 2D array to 3D array by inserting an axis at position 1
lst8 = np.expand_dims(lst8, axis=1)
print(lst8.shape)



(10,)
(10, 1)
(1, 10)
(10, 1, 1)
(5, 5)
(5, 1, 5)


# Question 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [6]:
lst9=np.arange(9).reshape(3,3)
lst10=np.arange(9,18).reshape(3,3)


print(np.vstack((lst9,lst10)))
print(np.hstack((lst9,lst10)))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[ 0  1  2  9 10 11]
 [ 3  4  5 12 13 14]
 [ 6  7  8 15 16 17]]


# Question 6:
How to get unique items and counts of unique items?

In [7]:
lst11 = np.array([[1,2,2,3,5],[5,6,6,7,8],[8,9,10,10,10]])

uniq,count= np.unique(lst11,return_counts=True)
print(uniq)
print(count)

[ 1  2  3  5  6  7  8  9 10]
[1 2 1 2 2 1 2 1 3]
